FROM condaforge/miniforge3

WORKDIR /backend/
RUN git clone https://github.com/AstraBert/learning-go
COPY ./data.py /backend/
COPY ./api.py /backend/
COPY ./agent.py /backend/
COPY ./conda_env.sh /backend/
COPY ./run.sh /backend/
COPY ./environment.yml /backend/

RUN bash conda_env.sh

CMD ["bash", "run.sh"]
